objects/Lease_Agreement__c/Lease_Agreement__c.object-meta.xml
<CustomObject>
    <label>Lease Agreement</label>
    <nameField>
        <displayFormat>LEASE-{0000}</displayFormat>
        <label>Lease Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lease_Agreement__c/fields/Agreed_Monthly_Rent__c.field-meta.xml
<CustomField>
    <fullName>Agreed_Monthly_Rent__c</fullName>
    <label>Agreed Monthly Rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Lease_Agreement__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Lease Agreements</relationshipLabel>
    <relationshipName>Lease_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Lease_Agreement__c/fields/Tenant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Tenant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tenant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lease Agreements</relationshipLabel>
    <relationshipName>Lease_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Stores data of the real estate Property</description>
    <label>Property</label>
    <nameField>
        <displayFormat>PROP-{0000}</displayFormat>
        <label>Property</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c/fields/Tenant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Tenant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tenant</description>
    <label>Tenant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tenant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/LeaseAgreementController.cls
public with sharing class LeaseAgreementController {
  @AuraEnabled
  public static Id createLease(
    Id tenantContactId,
    Id propertyId,
    String terms,
    Decimal agreedMonthlyRent,
    Date startDate,
    Date endDate
  ) {
    Lease_Agreement__c lease = new Lease_Agreement__c(
      Tenant_Contact__c = tenantContactId,
      Property__c = propertyId,
      Terms__c = terms,
      Agreed_Monthly_Rent__c = agreedMonthlyRent,
      Start_Date__c = startDate,
      End_Date__c = endDate
    );

    try {
      Database.insert(lease, AccessLevel.USER_MODE);
    } catch (DmlException ex) {
      throw new AuraHandledException(ex.getDmlMessage(0));
    }

    return lease.Id;
  }
}